### ISSUE TITLE
Challonge integration

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#197]
Integrate with Challonge API so they manage our tournaments.

* [x] Implement pushing logic #196
* [x] Implemented automation logic #198
* [x] Test on single games
* [x] Test on clanwars
* [x] Pass full scores #210
* [x] Tournaments page
* [x] Attach metadata, such as Clanwar ID. #211
* [ ] ~~Attach metadata, such as demo.~~ Removing, as #211 solves.
* [ ] ~~Support full clan names.~~ Removing, just a styling issue.
* [ ] Recoverability - if we're restarting when a clanwar happens. #212

Closing #172 and #176.

**Comment by ScalaWilliam** [comment]
![ca](https://cloud.githubusercontent.com/assets/2464813/21576373/519b84f6-cf67-11e6-8c88-0e84ffcbe046.png)

**Comment by ScalaWilliam** [comment]
<img width="463" alt="screen shot 2017-01-01 at 05 03 08" src="https://cloud.githubusercontent.com/assets/2464813/21579241/a55e8ac0-cfdf-11e6-9f58-6e7d0cfc86b0.png">

**Comment by ScalaWilliam** [comment]
* http://challonge.com/af_pi_woop/log
* http://challonge.com/af_test_tournament/log
* http://challonge.com/af_test_tournament_clanwar/log
* http://challonge.com/af_test_tournament/log

**Comment by ScalaWilliam** [comment]
Test was success

**Comment by ScalaWilliam** [comment]
Only #212 left - so closing this.
